In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report


df = pd.read_csv("C:/Users/Minseok/AI_CLASS/wine.csv")
df.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [2]:
X = df.drop(columns=['Wine'])  # 입력 변수
y = df['Wine']  # 타겟 변수


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [4]:

Y = pd.get_dummies(y).values

In [5]:
X = X.values

In [6]:
X


array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [7]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

In [8]:
Y


array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ T

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [19]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder

# 1️⃣ 데이터 로드
df = pd.read_csv("C:/Users/Minseok/AI_CLASS/wine.csv")

# 2️⃣ 원-핫 인코딩 전 (클래스 컬럼 확인)
print("🔹 원-핫 인코딩 전 (클래스 분포) 🔹")
print(df['Wine'].value_counts())  # 클래스 개수 확인
print(df.head(), "\n")  # 원본 데이터 출력

# 3️⃣ 원-핫 인코딩 수행
encoder = OneHotEncoder(sparse_output=False)  # OneHotEncoder 사용 (sparse_output=False)
y_onehot = encoder.fit_transform(df[['Wine']])  # 클래스 컬럼 변환

# 4️⃣ 원-핫 인코딩 후 (변환된 데이터 확인)
print("🔹 원-핫 인코딩 후 (변환된 데이터) 🔹")
print(y_onehot[:5])  # 처음 5개 샘플 확인

# 5️⃣ 입력 데이터와 출력 데이터 준비
X_train = df.drop(columns=['Wine'])  # 입력 데이터 (Class 제외)
y_train = y_onehot  # 원-핫 인코딩된 타겟 값

# 6️⃣ 모델 정의
model = Sequential()
model.add(Dense(10, input_shape=(13,), activation='relu'))  # ✅ input_shape=(13,)
model.add(Dense(8, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(y_train.shape[1], activation='softmax'))  # 클래스 개수만큼 출력층

# 7️⃣ 모델 컴파일
model.compile(optimizer=Adam(learning_rate=0.04), loss='categorical_crossentropy', metrics=['accuracy'])

# 8️⃣ 모델 구조 출력
model.summary()

🔹 원-핫 인코딩 전 (클래스 분포) 🔹
Wine
2    71
1    59
3    48
Name: count, dtype: int64
   Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735   

🔹 원-핫 인코딩 후 (변환된 데이터) 🔹
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


C:\Users\Minseok\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape       ┃    Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ dense (Dense)             │ (None, 10)         │        140 │
├───────────────────────────┼────────────────────┼────────────┤
│ dense_1 (Dense)           │ (None, 8)          │         88 │
├───────────────────────────┼────────────────────┼────────────┤
│ dense_2 (Dense)           │ (None, 6)          │         54 │
├───────────────────────────┼────────────────────┼────────────┤
│ dense_3 (Dense)           │ (None, 3)          │         21 │
└───────────────────────────┴────────────────────┴────────────┘

 Total params: 303 (1.18 KB)

 Trainable params: 303 (1.18 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# 1️⃣ 데이터 로드
df = pd.read_csv("C:/Users/Minseok/AI_CLASS/wine.csv")

# 2️⃣ 입력(X)과 출력(y) 분리
X = df.drop(columns=['Wine'])  # 입력 데이터 (13개 특징)
y = df['Wine'] - 1  # 클래스 값 (1부터 시작하는 것을 0부터 시작하도록 변환)

# 3️⃣ 데이터 표준화 (모델 학습을 위해 정규화)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4️⃣ 데이터 분할 (학습 80% / 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# 5️⃣ 원-핫 인코딩 수행
encoder = OneHotEncoder(sparse_output=False)
y_train_onehot = encoder.fit_transform(y_train.values.reshape(-1, 1))
y_test_onehot = encoder.transform(y_test.values.reshape(-1, 1))

# --------------------- [원-핫 인코딩 전후 비교] ---------------------
models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "SVM": SVC(kernel='linear', probability=True),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "MLP (Neural Network)": MLPClassifier(hidden_layer_sizes=(10, 8, 6), activation='relu', max_iter=500, random_state=42)
}

accuracy_results = {}

# 6️⃣ 각 모델별 학습 및 평가 (원-핫 인코딩 전)
print("🔹 머신러닝 모델 학습 중... (원-핫 인코딩 전)")
for model_name, model in models.items():
    model.fit(X_train, y_train)  # 모델 학습
    y_pred = model.predict(X_test)  # 예측
    acc = accuracy_score(y_test, y_pred)  # 정확도 계산
    accuracy_results[model_name] = {"No One-Hot": acc}
    print(f"✅ {model_name} 정확도 (원-핫 인코딩 전): {acc:.4f}")

# 7️⃣ 각 모델별 학습 및 평가 (원-핫 인코딩 후)
print("\n🔹 머신러닝 모델 학습 중... (원-핫 인코딩 후)")
for model_name, model in models.items():
    model.fit(X_train, np.argmax(y_train_onehot, axis=1))  # 모델 학습 (라벨을 다시 정수형으로 변환)
    y_pred_onehot = model.predict(X_test)  # 예측
    acc_onehot = accuracy_score(np.argmax(y_test_onehot, axis=1), y_pred_onehot)  # 정확도 계산
    accuracy_results[model_name]["One-Hot"] = acc_onehot
    print(f"✅ {model_name} 정확도 (원-핫 인코딩 후): {acc_onehot:.4f}")

# 8️⃣ 최종 결과 출력
print("\n📊 모델별 정확도 비교 📊")
for model_name, acc in accuracy_results.items():
    print(f"🔹 {model_name}: 원-핫 인코딩 전={acc['No One-Hot']:.4f}, 원-핫 인코딩 후={acc['One-Hot']:.4f}")


🔹 머신러닝 모델 학습 중... (원-핫 인코딩 전)
✅ Logistic Regression 정확도 (원-핫 인코딩 전): 1.0000
✅ SVM 정확도 (원-핫 인코딩 전): 0.9722
✅ Random Forest 정확도 (원-핫 인코딩 전): 1.0000
✅ MLP (Neural Network) 정확도 (원-핫 인코딩 전): 1.0000

🔹 머신러닝 모델 학습 중... (원-핫 인코딩 후)
✅ Logistic Regression 정확도 (원-핫 인코딩 후): 1.0000
✅ SVM 정확도 (원-핫 인코딩 후): 0.9722
✅ Random Forest 정확도 (원-핫 인코딩 후): 1.0000
✅ MLP (Neural Network) 정확도 (원-핫 인코딩 후): 1.0000

📊 모델별 정확도 비교 📊
🔹 Logistic Regression: 원-핫 인코딩 전=1.0000, 원-핫 인코딩 후=1.0000
🔹 SVM: 원-핫 인코딩 전=0.9722, 원-핫 인코딩 후=0.9722
🔹 Random Forest: 원-핫 인코딩 전=1.0000, 원-핫 인코딩 후=1.0000
🔹 MLP (Neural Network): 원-핫 인코딩 전=1.0000, 원-핫 인코딩 후=1.0000
